source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'execjs'
gem 'therubyracer'
#this is the current standard pagination plugin for rails
gem 'will_paginate'
#we are using this to build our SOAP services
gem 'wash_out'
gem 'rails-dbi', :require => 'dbi'
#we are using this to build unique job IDs
gem 'uuidtools'
#this is used to do some image processing like thumbnails and whatnot
gem 'rmagick', '2.13.2', :path => '/usr/local/lib/ruby/gems/1.9.1/gems/rmagick-2.13.2/' # you may not need this if you install on another system
gem 'nokogiri'
#alternative (better) and properly threaded correct webserver
#gem 'thin'
gem 'passenger'
#gem 'puma'
#dbi support
gem 'dbi'
gem 'dbd-mysql'
gem 'rubyzip', :require => 'zip/zip'
gem 'unicode_utils'

# soap4r in Ruby 1.9 requires the following fix
# http://www.ruby-forum.com/topic/3346702
# Edit gems/soap4r-1.5.8/lib/xsd/xmlparser.rb' line 66 from
# c.downcase == name
# to
# c.to_s.downcase == name
#
# Also add the line
# @internal_encoding = (RUBY_VERSION.to_f >= 1.9) ? 'UTF8' : $KCODEXML 
# to the top of the
# /usr/local/lib/ruby/gems/1.9.1/gems/soap4r-1.5.8/lib/soap/charset.rb
#
#This is used to query external SOAP 
gem 'soap4r-ruby1.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'
gem 'mysql'
gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development, :test do
    gem 'rspec-rails'
    gem 'factory_girl_rails'
end

group :test do
    gem 'faker'
    gem 'capybara'
    gem 'guard-rspec'
    gem 'launchy'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
